# Generated by Django 4.0.5 on 2022-06-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_user_order_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='api.order'),
        ),
    ]
